# Generated by Django 6.1.1 on 2026-09-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evento_id', models.CharField(max_length=36)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_medicion', models.DateTimeField()),
                ('fecha_hora_recepcion', models.DateTimeField()),
                ('origen', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'medicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion_id', models.BigIntegerField()),
                ('estado', models.CharField(max_length=8)),
                ('intervalo_esperado_segundos', models.PositiveIntegerField()),
                ('device_key_hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
    ]
