# Generated by Django 6.1.1 on 2026-09-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sala', models.CharField(max_length=100)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('rack', models.CharField(blank=True, max_length=100, null=True)),
                ('posicion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UmbralAmbiental',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=11)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('version', models.PositiveIntegerField()),
                ('vigente_desde', models.DateTimeField()),
            ],
            options={
                'db_table': 'umbral_ambiental',
                'managed': False,
            },
        ),
    ]
